repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-json

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.56.0
      hooks:
          - id: eslint
            args: ["--fix", "--config", ".eslintrc"]
            files: \.(js|jsx|ts|tsx)$
            exclude: ^build/

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v3.1.0"
      hooks:
          - id: prettier
            args: ["--write", "--config", ".prettierrc"]
            files: \.(js|jsx|json|css|ts|tsx|scss)$
            exclude: ^build/
